# -*- coding: utf-8 -*-
"""DeeP_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1bUdfpP9tKIPCVT4o-yJaKS5RLHIAjW

- SAKTHIVEL M
- 212222240088
- AIML
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        super().__init__()
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        return x

torch.manual_seed(32)
model = Model()

model.fc1.weight[0][0].item()

model.fc2.weight[0][0].item()



"""- SAKTHIVEL M
- 212222240088
- AIML

"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv('iris.csv')

df.head()

df.tail()

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(10,7))
fig.tight_layout()

plots = [(0,1),(2,3),(0,2),(1,3)]
colors = ['b', 'r', 'g']
labels = ['Iris setosa','Iris virginica','Iris versicolor']

for i, ax in enumerate(axes.flat):
    for j in range(3):
        x = df.columns[plots[i][0]]
        y = df.columns[plots[i][1]]
        ax.scatter(df[df['target']==j][x], df[df['target']==j][y], color=colors[j])
        ax.set(xlabel=x, ylabel=y)

fig.legend(labels=labels, loc=3, bbox_to_anchor=(1.0,0.85))
plt.show()

X = df.drop('target',axis=1)
y = df['target']

X

y

type(y)

#convert them into NumPy
X = X.values
y = y.values   # because libraries (like Scikit-Learn, TensorFlow, and PyTorch) require NumPy arrays as input instead of Pandas Series.

X

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=33)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)   # decrees 0.001

model.parameters

epoch = 100
losses = []
for i in range (epoch):
    y_pred = model.forward(X_train)
    loss = criterion(y_pred,y_train)
    losses.append(loss)
    if i % 10 == 0:
        print(f'Epoch {i} and loss is : {loss}')
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

plt.plot(range(epoch),[loss.detach().numpy() for loss in losses])
plt.ylabel('Loss')
plt.xlabel('Epoch');
plt.show()

"""-Validate the model with test set"""

with torch.no_grad():
    y_eval = model.forward(X_test)
    loss = criterion(y_eval,y_test)

loss

correct = 0
with torch.no_grad():
    for i,data in enumerate(X_test):
        y_val = model.forward(data)

        print(f'{i+1}).{str(y_val)} {y_test[i]}')
        if y_val.argmax().item() == y_test[i]:
            correct += 1
        print(f'we got {correct} correct')

correct = 0
with torch.no_grad():
    for i,data in enumerate(X_test):
        y_val = model.forward(data)

        print(f'{i+1}).   {str(y_val.argmax().item())}    {y_test[i]}')

"""- to save trained model to a file"""

torch.save(model.state_dict(),'michael_iris_model.pt')

new_model = Model()  # w or B
new_model.load_state_dict(torch.load('michael_iris_model.pt'))

new_model

mystery_iris = torch.tensor([5.6,3.7,2.2,0.5])

with torch.no_grad():
    print(new_model(mystery_iris))
    print(new_model(mystery_iris).argmax())